/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_5 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] adder
  );
  
  
  
  always @* begin
    if (alufn[0+0-:1] == 1'h1) begin
      adder = a - b;
    end else begin
      adder = a + b;
    end
  end
endmodule
