/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_5 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] adder
  );
  
  
  
  always @* begin
    
    case (alufn[0+1-:2])
      2'h0: begin
        adder = $signed(a) + $signed(b);
      end
      2'h1: begin
        adder = $signed(a) - $signed(b);
      end
      2'h2: begin
        adder = $signed(a) * $signed(b);
      end
      default: begin
        adder = 1'h0;
      end
    endcase
  end
endmodule
